FROM python:3.11-slim

WORKDIR /app

COPY ../src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../src/ .

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "56789"]